version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aws:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # keep only security updates and disable version updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
